"""`StagedEngine` — today's local cascade, behind the session contract (§2).

Silero segmenter → STT → (client-driven agent turn) → Kokoro/Edge synthesis.
Local-first, offline-capable, zero marginal cost. This is the default engine and
the only one on a build with no realtime credential.

What is deliberately UNCHANGED
------------------------------
The answer itself is still generated by the **client's** agent turn. The client
receives `transcript` frames, runs its normal chat pipeline (with all of its
conversation context, artifacts and history), and sends the reply back as
`speak` chunks for on-pod synthesis. Moving generation server-side would be a
far larger change to a path that already works, and it is not what fixes the
reported defects. The engine still observes the assistant text — it is handed
every chunk it is asked to synthesize — which is all the ledger needs.

What changes (design §2)
------------------------
1. **Ordered clip assembly.** Chunks are emitted as `AudioDelta` with a
   monotonic `seq`, and the ENGINE guarantees order. A chunk that falls back
   from Kokoro to Edge is still emitted in its original seq position, so a slow
   primary can no longer let a later chunk overtake an earlier one (defect 4).
   This is implemented as a reorder buffer: synthesis runs concurrently for
   throughput, emission is strictly sequential.

2. **Hold accounting is server-side.** The client keeps no "promised clips"
   counter. The engine emits exactly one `TurnComplete` once it has emitted
   every chunk of the turn, so there is no client-side count to leak and no
   watchdog to arm (defects 2 and 3).

3. **Nothing is silently lost.** A chunk whose synthesis fails emits
   `AudioDropped(seq, reason)` — the turn still advances, and the client can
   fall back for that chunk without stalling (Property 1).
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import AsyncIterator

from app.voice.engine import (
    AudioDelta, AudioDropped, EngineError, EnginePreflight, InterruptReason,
    Phase, PhaseChange, SpeechInterrupted, SttStatus, TranscriptDelta,
    TurnComplete,
    VoiceContext, VoiceEvent,
)
from app.voice import speaker as _speaker
from app.voice.turn_gate import is_meaningful

log = logging.getLogger("zapthetrick.voice.staged")

# How long a single chunk may spend in synthesis before the engine gives up on
# it and reports a drop. Generous: Edge fallback over a slow link is legitimate.
_SYNTH_TIMEOUT_S = 20.0

# Concurrent synthesis slots. >1 hides per-chunk latency; emission stays ordered
# regardless, so this only affects throughput, never correctness.
_SYNTH_CONCURRENCY = 2


class StagedSession:
    """One staged conversation over one socket."""

    def __init__(self, ctx: VoiceContext) -> None:
        self._ctx = ctx
        self._events: asyncio.Queue[VoiceEvent | None] = asyncio.Queue()
        self._closed = False

        # Generation: bumped on every confirmed interruption. Chunks tagged with
        # a stale generation are dropped BY VALUE at three points — enqueue,
        # post-synthesis, and emission — so bytes cannot outrun a barge-in.
        self._gen = 0

        # Ordered emission state.
        self._next_seq = 0            # next seq to emit
        self._pending: dict[int, tuple[bytes, bool]] = {}   # seq -> (audio,mp3)
        self._failed: dict[int, str] = {}                   # seq -> reason
        self._emitted = 0
        self._expected: int | None = None   # set when the client ends the reply

        # Turn assembly. `_chunk_text` maps a chunk's seq to its text, and only
        # SPOKEN seqs enter the transcript: a barge-in drops queued chunks, and
        # recording them would show the user text they never heard.
        self._user_text = ""
        self._chunk_text: dict[int, str] = {}
        self._spoken_seqs: list[int] = []
        self._assistant_parts: list[str] = []
        self._interrupted = False
        self._speaking = False

        self._sem = asyncio.Semaphore(_SYNTH_CONCURRENCY)
        self._tasks: set[asyncio.Task] = set()
        self._lock = asyncio.Lock()

        self._segmenter = None        # built lazily by attach_segmenter()
        self._recent_turns: list[str] = []

    # ── plumbing the runner uses ────────────────────────────────────────────

    @property
    def generation(self) -> int:
        return self._gen

    def bias_prompt(self) -> str | None:
        """Vocabulary/context biasing for STT: the configured seed plus THIS
        conversation's recent turns, so the decoder adapts to what is actually
        being discussed. Bounded — Whisper's prompt budget is ~224 tokens."""
        try:
            from app.core.config_loader import cfg
            seed = (getattr(cfg.stt, "prompt", "") or "").strip()
        except Exception:  # noqa: BLE001
            seed = ""
        if self._recent_turns:
            seed = (seed + " Recent: " + " ".join(self._recent_turns[-3:])).strip()
        return seed or None

    def set_speaking(self, on: bool) -> None:
        """The client reports playback state so a transcript heard DURING
        playback can be classified interrupt-vs-backchannel. Only then — a
        normal listening turn pays no classification latency."""
        self._speaking = bool(on)

    async def _emit(self, ev: VoiceEvent) -> None:
        if not self._closed:
            await self._events.put(ev)

    # ── STT callbacks (wired to the shared segmenter by the runner) ─────────

    async def on_utterance(self, text: str, full=None) -> None:
        t = (text or "").strip()
        if not t or not is_meaningful(t):
            return          # first-real-word gate: a cough never takes a turn

        # SPEAKER GATE (Requirement 12.2) — evaluated BEFORE turn admission and,
        # below, before interruption confirmation. A bystander must be able to do
        # neither. Fail-open: gate off / nobody enrolled / no embedder ⇒ admit,
        # so this cannot make a session worse than it is today.
        if not _speaker.admits_turn(self._ctx.speaker_profile, full):
            log.debug("staged: utterance rejected by the speaker gate")
            return

        self._recent_turns.append(t)
        del self._recent_turns[:-6]

        if self._speaking:
            # SEMANTIC barge-in: is the user taking the floor, or just following
            # along? Generalizes to paraphrases a word list cannot catch
            # ("hang on a second" vs "no I follow you").
            verdict = await self._classify_barge(t)
            if verdict == "backchannel":
                # Requirement 3.6 — an acknowledgement is not an interruption.
                await self._emit(TranscriptDelta("user", t, final=True))
                return
            if verdict == "interrupt":
                # Second gate point: only the enrolled speaker may cut the
                # assistant off mid-answer.
                if _speaker.admits_interruption(self._ctx.speaker_profile, full):
                    await self.interrupt(InterruptReason.SPEECH)

        self._user_text = t
        await self._emit(TranscriptDelta("user", t, final=True))
        await self._emit(PhaseChange(Phase.THINKING))

    async def on_partial(self, text: str) -> None:
        t = (text or "").strip()
        if not t:
            return
        # SEMANTIC COMPLETENESS on the partial: the client uses it to start
        # answering SPECULATIVELY while the user is still finishing (doc §6
        # Incremental Thinking). Computed with the SAME `completeness()` the
        # segmenter's adaptive endpointing uses — including interrogative-lead
        # detection for questions the ASR left un-'?'-ed — so the client never
        # needs its own heuristic. Fail-open: absent ⇒ no speculation.
        complete = False
        try:
            from app.live.hypothesis import completeness
            complete = completeness(t) == "complete"
        except Exception:  # noqa: BLE001
            complete = False
        await self._emit(TranscriptDelta("user", t, final=False,
                                         complete=complete))

    async def on_stt_status(self, kind: str, detail: str) -> None:
        # A dead mic stays EXPLAINABLE rather than silently producing nothing.
        await self._emit(SttStatus(str(kind or "error"), str(detail or "")))

    async def _classify_barge(self, text: str) -> str:
        """'interrupt' | 'backchannel' | '' (undecided → caller keeps current
        behaviour). Wraps the shared Live classifier read-only (rule L2)."""
        try:
            from app.live.barge_in import classify_utterance
            return await asyncio.to_thread(classify_utterance, text) or ""
        except Exception:  # noqa: BLE001
            return ""

    # ── VoiceSession contract ───────────────────────────────────────────────

    async def send_audio(self, pcm16: bytes) -> None:
        """Mic frames go to the shared segmenter, which owns turn detection on
        this path. Never blocks on synthesis."""
        seg = self._segmenter
        if seg is None or not pcm16:
            return
        try:
            import numpy as np
            arr = np.frombuffer(pcm16, dtype="<i2").astype("float32") / 32768.0
            if arr.size:
                await seg.push(arr)
        except Exception:  # noqa: BLE001
            log.debug("staged: bad pcm frame dropped", exc_info=True)

    async def send_text(self, text: str) -> None:
        """Typed input during a voice session — same path as a final
        transcript, minus the audio."""
        t = (text or "").strip()
        if not t:
            return
        self._user_text = t
        await self._emit(TranscriptDelta("user", t, final=True))
        await self._emit(PhaseChange(Phase.THINKING))

    def events(self) -> AsyncIterator[VoiceEvent]:
        async def _iter():
            while True:
                ev = await self._events.get()
                if ev is None:
                    return
                yield ev
        return _iter()

    async def interrupt(self, reason: InterruptReason,
                        played_ms: float | None = None,
                        played_chunks: int | None = None) -> None:
        """Atomic barge-in (Property 5): bump the generation, drop everything
        buffered for the old one, and close the turn out at that boundary.

        `played_chunks` is how many reply chunks the client actually RENDERED.

        This engine used to ignore what the client reported, on the reasoning
        that it already knew which chunks it had emitted. That reasoning was
        wrong, and an end-to-end run proved it: **emitted is not heard.** With
        fast synthesis the server pushes every chunk into the socket long before
        the user has heard the first one, so cutting on the emit boundary
        recorded three sentences when one was spoken. Only the client knows
        where hearing stopped.

        Chunks — not milliseconds — are the exact signal here, because this
        engine's transcript is already assembled per chunk. `played_ms` is
        accepted for signature parity with the realtime engine (whose audio is
        one continuous stream with no chunk boundaries to count) and is used as
        a fallback when the client reports only that."""
        async with self._lock:
            self._gen += 1
            self._interrupted = True
            # Cut the spoken record to what the client actually rendered.
            if played_chunks is not None and played_chunks >= 0:
                heard = int(played_chunks)
            elif played_ms is not None and played_ms <= 0:
                # The client played nothing, so nothing was heard. This is the
                # one thing a bare millisecond figure tells us for certain.
                heard = 0
            else:
                # Only a positive `played_ms`, with no per-chunk durations to map
                # it onto. Guessing a boundary here would invent a cut point, so
                # the emitted set stands — a client that wants an exact cut sends
                # `played_chunks`, which this engine's own model is built on.
                heard = None
            if heard is not None and heard < len(self._spoken_seqs):
                self._spoken_seqs = self._spoken_seqs[:heard]
            stale = sorted(self._pending)
            self._pending.clear()
            self._failed.clear()
        for seq in stale:
            await self._emit(AudioDropped(seq, "interrupted"))
        await self._emit(SpeechInterrupted(int(time.monotonic() * 1000), reason))
        await self._finish_turn()

    async def close(self) -> None:
        self._closed = True
        for t in list(self._tasks):
            t.cancel()
        self._tasks.clear()
        try:
            self._events.put_nowait(None)
        except Exception:  # noqa: BLE001
            pass

    # ── reply synthesis (driven by the client's `speak` frames) ─────────────

    async def speak(self, seq: int, text: str, *, voice: str = "",
                    speed: float = 1.0) -> None:
        """Queue one reply chunk for on-pod synthesis. `seq` is the client's
        chunk index within the current reply and defines emission order."""
        t = (text or "").strip()
        if not t:
            return
        gen = self._gen
        self._chunk_text[seq] = t
        self._assistant_parts.append(t)
        await self._emit(TranscriptDelta("assistant", t, final=False))
        task = asyncio.create_task(self._synth(seq, t, gen, voice, speed))
        self._tasks.add(task)
        task.add_done_callback(self._tasks.discard)

    async def reply_end(self, total_chunks: int | None = None) -> None:
        """The client has sent every chunk of this reply. The engine emits
        `TurnComplete` once it has emitted them all — this is the server-side
        hold accounting that replaces the client's leaky counter."""
        self._expected = (int(total_chunks) if total_chunks is not None
                          else self._next_seq + len(self._pending)
                          + len(self._failed))
        await self._drain()

    async def _synth(self, seq: int, text: str, gen: int, voice: str,
                     speed: float) -> None:
        if gen != self._gen:
            return                       # barged in before we even started
        audio = b""
        reason = ""
        try:
            async with self._sem:
                if gen != self._gen:
                    return
                from app.live import tts_synth
                coro = (tts_synth.synthesize(text, voice, speed=speed) if voice
                        else tts_synth.synthesize(text, speed=speed))
                audio = await asyncio.wait_for(coro, timeout=_SYNTH_TIMEOUT_S)
        except asyncio.TimeoutError:
            reason = "synthesis timeout"
        except asyncio.CancelledError:
            raise
        except Exception as exc:  # noqa: BLE001
            reason = f"synthesis failed: {str(exc)[:120]}"
        if gen != self._gen:
            return                       # barged in while synthesizing
        async with self._lock:
            if audio:
                self._pending[seq] = (bytes(audio), True)
            else:
                self._failed[seq] = reason or "empty synthesis"
        await self._drain()

    async def _drain(self) -> None:
        """Emit every contiguous chunk from `_next_seq` onward.

        This is the ordering guarantee: a chunk that finished early sits in
        `_pending` until its predecessors have been emitted, so a Kokoro→Edge
        fallback in the middle of a reply cannot reorder the reply.
        """
        while True:
            async with self._lock:
                seq = self._next_seq
                if seq in self._pending:
                    payload, mp3 = self._pending.pop(seq)
                    self._next_seq += 1
                    self._emitted += 1
                    self._spoken_seqs.append(seq)
                    ev: VoiceEvent = AudioDelta(seq, payload, mp3=mp3)
                elif seq in self._failed:
                    reason = self._failed.pop(seq)
                    self._next_seq += 1
                    ev = AudioDropped(seq, reason)
                else:
                    break
            if isinstance(ev, AudioDelta):
                await self._emit(PhaseChange(Phase.SPEAKING))
            await self._emit(ev)
        await self._maybe_complete()

    async def _maybe_complete(self) -> None:
        if self._expected is None:
            return
        async with self._lock:
            done = (self._next_seq >= self._expected
                    and not self._pending and not self._failed)
        if done:
            await self._finish_turn()

    async def _finish_turn(self) -> None:
        """Exactly one TurnComplete per turn, then back to listening."""
        user = self._user_text
        # Only what was actually spoken. On a clean turn this is every chunk; on
        # an interrupted one it stops where playback stopped, so the recorded
        # answer matches what the user heard rather than what we intended to say.
        if self._interrupted and self._spoken_seqs:
            assistant = " ".join(
                self._chunk_text.get(s2, "")
                for s2 in sorted(self._spoken_seqs)).strip()
        elif self._interrupted:
            assistant = ""
        else:
            assistant = " ".join(p for p in self._assistant_parts if p).strip()
        if not user and not assistant:
            self._reset_turn()
            return
        await self._emit(TurnComplete(user=user, assistant=assistant,
                                      interrupted=self._interrupted,
                                      chunks=self._emitted))
        await self._emit(PhaseChange(Phase.LISTENING))
        self._reset_turn()

    def _reset_turn(self) -> None:
        self._user_text = ""
        self._assistant_parts = []
        self._chunk_text.clear()
        self._spoken_seqs.clear()
        self._interrupted = False
        self._emitted = 0
        self._expected = None
        self._next_seq = 0
        self._pending.clear()
        self._failed.clear()

    # ── segmenter wiring (runner calls this once) ──────────────────────────

    def attach_segmenter(self, segmenter) -> None:
        self._segmenter = segmenter


class StagedEngine:
    """The local cascade. Always available — no credential, no network."""

    name = "staged"

    def preflight(self) -> EnginePreflight:
        # Loads nothing: the STT model is already resident and shared, and
        # tts_synth resolves its backend lazily on first use.
        return EnginePreflight(ok=True, turn_detection="server_vad")

    async def open(self, ctx: VoiceContext) -> StagedSession:
        return StagedSession(ctx)


__all__ = ["StagedEngine", "StagedSession"]
