"""Initial schema — DataBaseArchitecture.md tables.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-15

Hand-rolled (not autogenerated) so the comments + computed columns
match the spec exactly. Subsequent migrations should use
`alembic revision --autogenerate`.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR, UUID


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- users ----
    op.create_table(
        "users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("preferences", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )

    # ---- resumes ----
    op.create_table(
        "resumes",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=True),
        sa.Column("filename", sa.Text, nullable=False),
        sa.Column("file_path", sa.Text, nullable=False),
        sa.Column("display_name", sa.Text, nullable=False, server_default="Resume"),
        sa.Column("profile", JSONB, nullable=False),
        sa.Column("raw_text", sa.Text, nullable=False, server_default=""),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("active", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("embedding_model", sa.Text, nullable=False),
    )
    op.create_index("ix_resumes_user_active", "resumes", ["user_id", "active"])

    # ---- resume_chunks ----
    op.create_table(
        "resume_chunks",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("resume_id", UUID(as_uuid=True), sa.ForeignKey("resumes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("parent_id", UUID(as_uuid=True), nullable=True),
        sa.Column("level", sa.SmallInteger, nullable=False, server_default="1"),
        sa.Column("section_type", sa.Text, nullable=True),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("entity_tags", ARRAY(sa.Text), nullable=True),
        sa.Column("vector_point_id", UUID(as_uuid=True), nullable=True),
        sa.Column("position", sa.Integer, nullable=False, server_default="0"),
        sa.Column(
            "content_tsv",
            TSVECTOR,
            sa.Computed("to_tsvector('english', content)", persisted=True),
        ),
    )
    op.create_index("ix_resume_chunks_resume", "resume_chunks", ["resume_id"])
    op.create_index("ix_resume_chunks_parent", "resume_chunks", ["parent_id"])
    op.create_index(
        "ix_resume_chunks_tsv", "resume_chunks", ["content_tsv"], postgresql_using="gin"
    )

    # ---- sessions ----
    op.create_table(
        "sessions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("resume_id", UUID(as_uuid=True), nullable=True),
        sa.Column("type", sa.String(20), nullable=False, server_default="chat"),
        sa.Column("title", sa.Text, nullable=False, server_default="New session"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("metadata", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])

    # ---- messages ----
    op.create_table(
        "messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("session_id", UUID(as_uuid=True), sa.ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("tokens", sa.Integer, nullable=True),
        sa.Column("model", sa.Text, nullable=True),
        sa.Column("provider", sa.Text, nullable=True),
        sa.Column("latency_ms", sa.Integer, nullable=True),
        sa.Column("intent", sa.String(50), nullable=True),
        sa.Column("agents_used", ARRAY(sa.Text), nullable=True),
        sa.Column("sources", JSONB, nullable=True),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column(
            "content_tsv",
            TSVECTOR,
            sa.Computed("to_tsvector('english', content)", persisted=True),
        ),
    )
    op.create_index("ix_messages_session_created", "messages", ["session_id", "created_at"])
    op.create_index("ix_messages_tsv", "messages", ["content_tsv"], postgresql_using="gin")

    # ---- feedback ----
    op.create_table(
        "feedback",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("message_id", UUID(as_uuid=True), sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=True),
        sa.Column("episode_id", UUID(as_uuid=True), nullable=True),
        sa.Column("signal", sa.String(20), nullable=False),
        sa.Column("payload", JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ---- agent_runs ----
    op.create_table(
        "agent_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("session_id", UUID(as_uuid=True), nullable=True),
        sa.Column("message_id", UUID(as_uuid=True), nullable=True),
        sa.Column("agent", sa.Text, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(20), nullable=True),
        sa.Column("input_summary", JSONB, nullable=True),
        sa.Column("output_summary", JSONB, nullable=True),
        sa.Column("tokens", sa.Integer, nullable=True),
        sa.Column("cost_estimate", sa.Numeric(12, 6), nullable=True),
    )
    op.create_index("ix_agent_runs_session_id", "agent_runs", ["session_id"])

    # ---- model_usage ----
    op.create_table(
        "model_usage",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("provider", sa.Text, nullable=True),
        sa.Column("model", sa.Text, nullable=True),
        sa.Column("role", sa.Text, nullable=True),
        sa.Column("prompt_tokens", sa.Integer, nullable=True),
        sa.Column("completion_tokens", sa.Integer, nullable=True),
        sa.Column("latency_ms", sa.Integer, nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # ---- episodes ----
    op.create_table(
        "episodes",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("session_tag", sa.String(64), nullable=False),
        sa.Column("question", sa.Text, nullable=False),
        sa.Column("draft", sa.Text, nullable=False, server_default=""),
        sa.Column("final", sa.Text, nullable=False),
        sa.Column("intent", sa.String(50), nullable=False, server_default="general"),
        sa.Column("sources", JSONB, nullable=True),
        sa.Column("tools_called", JSONB, nullable=True),
        sa.Column("latency_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("feedback", sa.String(10), nullable=True),
        sa.Column("feedback_payload", JSONB, nullable=True),
        sa.Column("vector_point_id", UUID(as_uuid=True), nullable=True),
        sa.Column("question_embedding", JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_episodes_session_tag", "episodes", ["session_tag"])

    # ---- skills ----
    op.create_table(
        "skills",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("session_tag", sa.String(64), nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("kind", sa.String(20), nullable=False, server_default="preference"),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=False, server_default="0.5"),
        sa.Column("evidence_episode_ids", JSONB, nullable=True),
        sa.Column("vector_point_id", UUID(as_uuid=True), nullable=True),
        sa.Column("text_embedding", JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_skills_session_tag", "skills", ["session_tag"])


def downgrade() -> None:
    for tbl in (
        "skills",
        "episodes",
        "model_usage",
        "agent_runs",
        "feedback",
        "messages",
        "sessions",
        "resume_chunks",
        "resumes",
        "users",
    ):
        op.drop_table(tbl)
